### ISSUE TITLE
substr 截取路径导致的 bug

### ISSUE THREAD

**Issue by yeojongki** [JasKang/vite-plugin-md-preview#14]
关于 `plugin.ts` 中 `resolveId`、`transform`、`load` 这几个方法获取路径疑问
1. [resolveId](https://github.com/JasKang/vite-plugin-vuedoc/blob/master/packages/vite-plugin-vuedoc/src/plugin.ts#L49)
2. [load ](https://github.com/JasKang/vite-plugin-vuedoc/blob/master/packages/vite-plugin-vuedoc/src/plugin.ts#L60)
3. [transform ](https://github.com/JasKang/vite-plugin-vuedoc/blob/master/packages/vite-plugin-vuedoc/src/plugin.ts#L70)

为什么要截取路径 (即`substr(1)`)，是有什么特殊情况？我创建了一个 `monorepo` 项目，发现会有`bug`，目录结构如下：

lerna-vite-test
├── docs   ------------------------------ vite 项目
│   ├── index.html
│   ├── package.json
│   ├── public
│   │   └── favicon.ico
│   ├── README.md
│   ├── src
│   │   ├── App.tsx --------------------- 在这里引入了 packages 目录下的文件
│   │   ├── assets
│   │   ├── components
│   │   ├── main.ts
│   │   └── shims-vue.d.ts
│   ├── tsconfig.json
│   ├── vite.config.ts
│   └── yarn.lock
├── lerna.json
├── package.json
├── packages  ------------------------ 存放 md 项目位置
│   └── button
│       ├── package.json
│       └── src
└── yarn.lock

调试过后发现是路径有误：
1. 原本的路径是 `D:/XXX`, 
2. 经过 `substr` 后变成 `:/XXX`，少了 `盘符D`
3. 拼接后这个路径肯定是有问题的 (`path.join(config.root, id.substr(1)`)

复现 repo: https://github.com/yeojongki/lerna-vite-docs-issue
**注：我的环境是 `windows`**

我的解决方法：将 `resolveId`、`transform`、`load` 这几个方法获取路径相关地方不用 `substr` 拼接，使用原路径即可

**Comment by JasKang** [comment]
针对 windows 环境下的路径转换确实还需要进一步处理
不过你这里的问题在于 vite 有个 root 目录, 默认是 cwd ，模块解析都是相对于这个 root 目录的。而你的 md 文件并不在 vite 执行目录中，这样还是会有问题的

**Comment by yeojongki** [comment]
@JasKang 如果将那几个拼接路径的地方移除掉 `substr(1)`，是否会对其他非 `windows` 操作系统有影响？

**Comment by yeojongki** [comment]
@JasKang 那目前来说是解析不了非 root 目录的文件吗？
