### ISSUE TITLE
加载md文件报错

### ISSUE THREAD

**Issue by ammagician** [JasKang/vite-plugin-md-preview#28]
当md文件里面使用···vue demo时就会报错
![image](https://user-images.githubusercontent.com/11594163/147719343-c28ef134-77a9-4225-9c51-d919efe72e12.png)

![image](https://user-images.githubusercontent.com/11594163/147719201-81a4c8d3-c2b1-43a2-9067-6fcec9484afd.png)

vite版本为2.7.2
vue版本为3.2.25

**Comment by ammagician** [comment]
更正信息：与vite、vue的版本没有关系
当在package.json增加一下信息时会报错
![image](https://user-images.githubusercontent.com/11594163/147729426-1caf5a94-7d16-4ed7-a1fd-add55d03fc63.png)

**Comment by JasKang** [comment]
新版已处理

**Comment by elarbor** [comment]
> 新版已处理

可以开通仓库的discussion模块吗
