### ISSUE TITLE
版本有缺陷

### ISSUE THREAD

**Issue by luocong2016** [JasKang/vite-plugin-md-preview#32]
error when starting dev server:
Error [ERR_REQUIRE_ESM]: require() of ES Module

**Comment by SmileCorporation** [comment]
> error when starting dev server: Error [ERR_REQUIRE_ESM]: require() of ES Module

这种情况在自己项目里设置一下 package.json 中  "type": "module",   可解决

**Comment by JasKang** [comment]
resolved
