### ISSUE TITLE
使用"vite-plugin-md": "^0.20.2"vue组件并没有被解析出来

### ISSUE THREAD

**Issue by u373693041** [JasKang/vite-plugin-md-preview#35]
![image](https://user-images.githubusercontent.com/48196776/186093574-014af3f0-122c-4deb-9f43-1e76a02697ef.png)
使用vite-plugin-md 0.13后，又会面临路径问题https://github.com/JasKang/vite-plugin-md-preview/issues/34

**Comment by JasKang** [comment]
resolved
